apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv-jegan
  namespace: jegan
  labels:
    name: jegan
spec:
  capacity:
    storage: 500Mi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /mnt/mysql
    server: 192.168.1.80
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc-jegan
  namespace: jegan 
spec:
  selector:
    matchLabels:
       name: jegan 
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 500Mi
---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-credentials
  namespace: jegan
data:
  username: cm9vdA==
  password: cm9vdEAxMjM=  
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: jegan
  labels:
    app: mysql
  name: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - image: bitnami/mysql:latest
        name: mysql
        env:
         - name: MYSQL_ROOT_PASSWORD
           valueFrom: 
             secretKeyRef: 
                name: mysql-credentials
                key: password
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /bitnami/mysql/data
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pvc
---
apiVersion: v1
kind: Service
metadata:
  namespace: jegan
  labels:
    app: mysql
  name: mysql
  namespace: tektutor
spec:
  ports:
  - port: 3306
    protocol: TCP
    targetPort: 3306
  selector:
    app: mysql
  type: ClusterIP
