spec:
  template:
    spec:
      containers:
        - env:
          - name: jdbc-connection-string 
            valueFrom:
             configMapKeyRef:
                name: jdbc-configmap 
                key: jdbc 
          - name: db-user
            valueFrom:
              secretKeyRef:
                 name: mysql-credentials 
                 key: username
          - name: db-password
            valueFrom:
              secretKeyRef:
                 name: mysql-credentials 
                 key: password 
